### ISSUE TITLE
Migrate to using VirtualCodebase from the latest scancode

### ISSUE THREAD

**Issue by majurg** [nexB/deltacode#101]
`scancode-toolkit` can re-create a Codebase object and its Resource (files, dirs) from a scancode json results file. 

It will useful to convert DeltaCode to using this VirtualCodebase object as the means of doing all the delta operations. Their natural tree structure makes traversing a scan easier, and a variety of other delta operations become easier to do. We also wont have to maintain as many python Objects as we do now; most of these are replicated in a VirtualCodebase (License, Copyright, etc)

**Comment by pratik0316** [comment]
@majurg , @johnmhoran I can not get this following line :

> scancode-toolkit can re-create a Codebase object and its Resource (files, dirs) from a scancode json results file.

What I know is scancode can generate a json output upon scanning a particular codebase,
using this or similar related commands ::
`./scancode -clip --json-pp - samples
`

So basically I want to know what does `CodeBase object` and `Virtual codebase` refers in this context.
Can you please clarify it ,as I would like to solve this issue done

**Comment by steven-esser** [comment]
See https://github.com/nexB/scancode-toolkit/blob/54f5f689b9be958f3bd871536a5ce3d34a115255/src/scancode/resource.py#L1384

**Comment by pratik0316** [comment]
Thanks @majurg for the explanation 😃

**Comment by kjuq** [comment]
@majurg @arnav-mandal1234 Hello. I have 2 questions.

* Do I have to write a concrete plan on GSoC proposal? In other words, is a specific description (like, "This and this will be replaced by using VirtualCodebase. The returning values should be like this. Arguements are... etc.) needed?
* Or, are general understanging and strict scheduling important/enough?

Thanks.

**Comment by steven-esser** [comment]
@kvoj the more detailed, the better.

**Comment by kjuq** [comment]
@majurg Okay. Thank you.
