### ISSUE TITLE
Add 'status' field to similar to Delta object

### ISSUE THREAD

**Issue by steven-esser** [nexB/deltacode#110]
Parent Ticket: #107 
Related Ticket: #109 

We need to add a status field to our Delta object that will hold one of our 'status' values: removed, modified, etc

These were previously added via factors list, so we need to break this out into its own field.

**Comment by iamsid2** [comment]
is this issue still open?

**Comment by steven-esser** [comment]
@iamsid2 Yes

**Comment by arnav-mandal1234** [comment]
@majurg 
I am new here. Can I work on this issue?
