### ISSUE TITLE
GSOC-2019

### ISSUE THREAD

**Issue by riya-17** [nexB/deltacode#119]
Hey @majurg @johnmhoran
I am interested in this issue for GSOC-2019 I know it is too late but I would still like to give it a shot. 
Can you tell me how I can start with it?

**Comment by steven-esser** [comment]
Please see https://github.com/nexB/aboutcode/wiki/GSOC-2019

**Comment by riya-17** [comment]
@majurg  I have been through this link. Can I get some brief intro regarding the project or some issue related to it

**Comment by steven-esser** [comment]
@riya-17 All the project information is in that link. 

Take a look around at all of our GH repos and try to solve some issues.

**Comment by riya-17** [comment]
@majurg ok, Thank you
