### ISSUE TITLE
Support in Windows 10 64 bit

### ISSUE THREAD

**Issue by iamsid2** [nexB/deltacode#121]
Deltacode is currently unsupported in Windows 10 64 bit version
![2019-04-05](https://user-images.githubusercontent.com/23580835/55611699-ed0f4f00-57a3-11e9-89c3-126d4a35f0fb.png)

**Comment by pombredanne** [comment]
Actually, using Python 64 bits on Windows in not supported. And this is a Scancode issue https://github.com/nexB/scancode-toolkit/issues/335
You can run on Win64 using Python32

**Comment by steven-esser** [comment]
#162 is merged, which drops support for Python2 and adds support for python3. 64bit on Windows should work I believe.
