### ISSUE TITLE
Merge DeltaCode into ScanCode

### ISSUE THREAD

**Issue by mjherzog** [nexB/deltacode#125]
We need to plan for merging DeltaCode into ScanCode Toolkit sooner than later. Since DeltaCode operates on Scan files we should include in ScanCode TK at a minimum in order to treat it as a TK module and keep it in synch with the other TK modules.  This will require design especially since ScanCode operates on a pair of Scan files and is therefore not an obvious candidate for running from the main ScanCode command line.

**Comment by steven-esser** [comment]
We could follow an approach similar to `extractcode`, which has its own cli command and set of options.

**Comment by mjherzog** [comment]
This sounds right.

**Comment by mjherzog** [comment]
Reconsidering whether this is actually a good idea. We probably should avoid over loading ScanCode Toolkit with too many disparate functions.
