### ISSUE TITLE
Upgrade DeltaCode to Python 3

### ISSUE THREAD

**Issue by mjherzog** [nexB/deltacode#131]
DeltaCode needs to use the same version of Python as ScanCode Toolkit.  This issue is to upgrade to match Toolkit v3.x - from that point on we need to keep DeltaCode in sync with SC Toolkit for Python and for any shared dependencies.

**Comment by kjuq** [comment]
@arnav-mandal1234 @majurg 
Hello. I'm very interested in this issue (along with #101 and #102) as my project of GSoC 2020; [Support Python3 in DeltaCode and other improvements](https://github.com/nexB/aboutcode/wiki/Project-Ideas-DeltaCode-Python3). 
However, #101 looks like being in progress. Is this issue still one of GSoC project?
Can I submit the proposal of this project idea?

**Comment by arnav-mandal1234** [comment]
@kvoj Yes, sure. Please join the Gitter channel and submit a draft proposal.

**Comment by kjuq** [comment]
@arnav-mandal1234 Thank you for your response. Okay, I will finish writing the proposal as soon as possible and submit it via Gitter.

**Comment by steven-esser** [comment]
#162 merged, closing this.
