### ISSUE TITLE
Create DeltaCode documentation on ReadTheDocs

### ISSUE THREAD

**Issue by mjherzog** [nexB/deltacode#133]
The primary DeltaCode documentation is currently at the top of the AboutCode website on ReadtheDocs (RTD). It should be moved to its own RTD website. This task will also:
- Include cross-checking it with the Wiki documentation and then removing the Wiki pages
- Versioning the DeltaCode RTD website in sync with the code.

**Comment by ankit2001** [comment]
Do u want a separate blog for documentation ??

**Comment by mjherzog** [comment]
Our goal here is to move the DeltaCode documentation from https://aboutcode.readthedocs.io/en/latest/deltacode/index.html to https://readthedocs.org/projects/deltacode/.  
This will also require moving the corresponding file from https://github.com/nexB/aboutcode/tree/master/docs/source/deltacode to https://github.com/nexB/deltacode/tree/develop/docs.

**Comment by ankit2001** [comment]
okk thanks @mjherzog

**Comment by AyanSinhaMahapatra** [comment]
Also remove the old wikis and only link to the respective RTD pages for all of the wiki pages.

**Comment by mjherzog** [comment]
Please move the existing RTD doc from AboutCode to DeltaCode on RTD.org. Ayan can assist you as needed.

**Comment by chinyeungli** [comment]
Documentation is moved to https://deltacode.readthedocs.io/en/latest/deltacode/index.html#
