### ISSUE TITLE
Linux and MacOs buid is showing some warnings in TravisCI

### ISSUE THREAD

**Issue by pratik0316** [nexB/deltacode#146]
Currently the mac os and linux build is showing approximately(11) warnings upon its execution,where the running `TEST SUITE` is `$PYTEST` 
The below warning  is for linux build
![Screenshot from 2020-03-20 10-02-42](https://user-images.githubusercontent.com/44219625/77137019-1a770a80-6a92-11ea-969f-09f6ed4d56aa.png)
The below warning is for mac os build
![Screenshot from 2020-03-20 10-03-12](https://user-images.githubusercontent.com/44219625/77137036-29f65380-6a92-11ea-83e9-c94adea65f9f.png)

**Comment by pratik0316** [comment]
If this is a bug I would like to solve it.

**Comment by steven-esser** [comment]
This is low priority and not really something you should spend time on.

**Comment by pratik0316** [comment]
okay @majurg
