### ISSUE TITLE
configure failed,why?

### ISSUE THREAD

**Issue by 00032118** [nexB/deltacode#153]
D:\scancode\deltacode-1.0.0>python --version
Python 3.6.0

D:\scancode\deltacode-1.0.0>configure
* Activating ...
* Installing components ...
Requirement already satisfied: pip in d:\scancode\deltacode-1.0.0\lib\site-packages (from -r D:\scancode\deltacode-1.0.0\etc\conf\base.txt (line 5))
Collecting pytest (from -r D:\scancode\deltacode-1.0.0\etc\conf\dev\base.txt (line 2))
  Could not find a version that satisfies the requirement pytest (from -r D:\scancode\deltacode-1.0.0\etc\conf\dev\base.txt (line 2)) (from versions: )
No matching distribution found for pytest (from -r D:\scancode\deltacode-1.0.0\etc\conf\dev\base.txt (line 2))

Failed to execute command:
pip install --no-allow-external --use-wheel --no-index --no-cache-dir --find-links="D:\scancode\deltacode-1.0.0\thirdparty/prod" --find-links="D:\scancode\deltacode-1.0.0\thirdparty/base" -r "D:\sc
ode\deltacode-1.0.0\etc\conf\dev\base.txt". Aborting...

**Comment by steven-esser** [comment]
DeltaCode does not support python3 at this time. Eventually we will, but for now you can check this ticket for status of the migration: #131

**Comment by 00032118** [comment]
(deltacode-1.0.0) D:\scancode\deltacode-1.0.0>python --version
Python 2.7.14

(deltacode-1.0.0) D:\scancode\deltacode-1.0.0>configure
* Activating ...
* Installing components ...
Requirement already satisfied: pip in d:\scancode\deltacode-1.0.0\lib\site-packages (from -r
Collecting pytest (from -r D:\scancode\deltacode-1.0.0\etc\conf\dev\base.txt (line 2))
  Could not find a version that satisfies the requirement pytest (from -r D:\scancode\deltac
No matching distribution found for pytest (from -r D:\scancode\deltacode-1.0.0\etc\conf\dev\

Failed to execute command:
pip install --no-allow-external --use-wheel --no-index --no-cache-dir --find-links="D:\scanc
ode\deltacode-1.0.0\etc\conf\dev\base.txt". Aborting...

**Comment by pratik0316** [comment]
@00032118 is  `bin` directory in the deltacode directory?

**Comment by pratik0316** [comment]
@00032118 I think it is still using py3 during config , else it will not show this error.

**Comment by 00032118** [comment]
(deltacode-1.0.0) D:\scancode\deltacode-1.0.0>ls
AUTHORS.rst       Lib          README.rst          configure        deltacode.bat  setup.py
CHANGELOG.rst     MANIFEST.in  Scripts             configure.bat    etc            src
CONTRIBUTING.rst  NOTICE       apache-2.0.LICENSE  deltacode        samples        tcl
Include           PKG-INFO     bin                 deltacode.ABOUT  setup.cfg      thirdparty

> @00032118 is `bin` directory in the deltacode directory?

no, it's deltacode root path

**Comment by 00032118** [comment]
(deltacode-1.0.0) D:\scancode\deltacode-1.0.0>ls
AUTHORS.rst       Lib          README.rst          configure        deltacode.bat  setup.py
CHANGELOG.rst     MANIFEST.in  Scripts             configure.bat    etc            src
CONTRIBUTING.rst  NOTICE       apache-2.0.LICENSE  deltacode        samples        tcl
Include           PKG-INFO     bin                 deltacode.ABOUT  setup.cfg      thirdparty

**Comment by pratik0316** [comment]
yeah so bin  dir is created,

> (deltacode-1.0.0) D:\scancode\deltacode-1.0.0>ls
> AUTHORS.rst Lib README.rst configure deltacode.bat setup.py
> CHANGELOG.rst MANIFEST.in Scripts configure.bat etc src
> CONTRIBUTING.rst NOTICE apache-2.0.LICENSE deltacode samples tcl
> Include PKG-INFO `bin` deltacode.ABOUT setup.cfg thirdparty

**Comment by pratik0316** [comment]
do ls in the bin directory, and show the contents

**Comment by steven-esser** [comment]
@00032118 If you are on windows, you may want to try running `configure.bat`

**Comment by steven-esser** [comment]
#162 adds support for Python3 and windows 64 bit. This should be working now. Closing.
