### ISSUE TITLE
In the output content format ‘[ ’how to understand？

### ISSUE THREAD

**Issue by 00032118** [nexB/deltacode#161]
{"name": "[[", "path": "bin/[[", "date": "2020-05-13", "file_type": "ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped", "checksum_type": "sha256", "checksum": "6850ec94fba631d36d4fa66d335cb1b939cfc8de09b52475eda8d6f822f4d92b", "version_control": "", "version": "", "extattrs": "-rwxr-xr-x|0|0|1132800|398", "licenses": ["bin/[[:GPL 2.0", "bin/[[:GPL 1.0 or later"], "license_expressions": ["gpl-2.0", "gpl-1.0-plus"],

**Comment by pratik0316** [comment]
@00032118 please refer to the docs, is it comming in the same line?

**Comment by steven-esser** [comment]
@00032118 It seems like the file in question is named `[[`, which makes the output look a little strange. 

Or is there some other issue you are trying to bring up here.
