### ISSUE TITLE
Create objects to score scan information

### ISSUE THREAD

**Issue by steven-esser** [nexB/deltacode#172]
We should abstract the following lines into a separate object for readability: https://github.com/nexB/deltacode/blob/a09514623fc51222230f356a6f911f3e70086cdc/src/deltacode/__init__.py#L74-L77

**Comment by steven-esser** [comment]
Alternatively, we could remove these entirely; @Pratikrocks where are these fields used?

**Comment by pratik0316** [comment]
`self.new_files_errors` are used to collect error logs if any 
similarly for the `self.old_files_error`

Now I have added `self.new_scan_options` to collect the `options` headers in the `VirtualCodebase` .
We could `Aggregate` in separate areas too

**Comment by steven-esser** [comment]
I understand you may collect these things, but are they ever used outside of that?

**Comment by pratik0316** [comment]
We can get rid of the `self.new_files_errors`  and ``self.old_files_errors``, as such its not used, and basically remaining empty only, i am removing it
But we need the `self.new_scan_options` and `self.old_scan_options`

**Comment by steven-esser** [comment]
Does a virtualcodebase contain any information relating to scan options?

**Comment by pratik0316** [comment]
Yes it does in the headers sections!
