### ISSUE TITLE
Check and determine ScanCode options present in a ScanCode data file

### ISSUE THREAD

**Issue by johnmhoran** [nexB/deltacode#2]
In order to compare codebases accurately, Deltacode needs scancode data files that have the full file information available, at the very least.

We also need to know what additional scancode options each Deltacode input file has in order to figure out what other scan data is present and therefore what type of license, copyright or other data we can compare.

**Comment by arnav-mandal1234** [comment]
@majurg Can you please explain me the issue?
I want to work on this issue. :)
