### ISSUE TITLE
List DeltaCode as a package in Pypi

### ISSUE THREAD

**Issue by majurg** [nexB/deltacode#99]
We should list DeltaCode alongside scancode-toolkit as an official pypi package. 

This aid in installation and allow users to just `pip install deltacode`.

**Comment by Sai-Adarsh** [comment]
This interests me. What should I work on?

**Comment by pombredanne** [comment]
@Sai-Adarsh thank you. We have a setup and everything ... so this is really a maintainer task to publish this. Nothing that you could help with! ... which is why this is assigned to @majurg

**Comment by steven-esser** [comment]
DeltaCode can now be install via `pip install deltacode`. The PyPI project page can be found here: https://pypi.org/project/deltacode/

Future releases of DeltaCode will continue to be pushed to pypi and installable via `pip`.
